[phases.setup]
nixPkgs = ["go_1_23"]

[phases.install]
cmds = ["cd backend && go mod download"]

[phases.build]
cmds = ["cd backend && go build -o bin/api ./cmd/api"]

[start]
cmd = "cd backend && ./bin/api"

